---
- name: SSH Operations
  hosts: all
  become: true
  tasks:
    # - name: Remove any PermitRootLogin instruction
    #   ansible.builtin.lineinfile:
    #     path: /etc/ssh/sshd_config
    #     regexp: ^PermitRootLogin
    #     state: absent

    # - name: Disable ssh root login
    #   ansible.builtin.lineinfile:
    #     path: /etc/ssh/sshd_config
    #     regexp: ^PermitRootLogin
    #     line: PermitRootLogin no
    #     state: present

    - name: Enable root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: ^PermitRootLogin
        line: PermitRootLogin yes

    - name: Disable password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: ^PasswordAuthentication
        line: PasswordAuthentication no

    - name: Add the public key to the root login
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: '0600'

    - name: Enable ssh on port 8443 in ssh config
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: ^Port
        line: Port 8443
        validate: /usr/sbin/sshd -t -f %s

    - name: Restart ssh service
      ansible.builtin.service:
        name: sshd
        state: restarted

